---
title: "R Exercises Session 8"
author: "Introduction to R for Data Management and Analysis"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

First, clone the [Assignment8][1] repository to your own GitHub account
by forking. Look for the forking button on the GitHub repository page.

You can then modify the repository (namely the `R_Exercises8.Rmd` file)
and complete the assignment by adding your answers in the appropriate
place. Do **NOT** rename the file.

## Completing the assignment

Check your work by knitting the document.

1. Create a level 2 header below in Markdown with the name "Answer 1".
 "Answer 1"
 **


2. Add an unordered Markdown list of your favorite food dishes and
add their ingredients as sub-items in the list. You should enter at least two
dishes with two ingredients each.
= **myfaves- c("Rice", "Fishcurry", "Meatcurry") myfaves "Rice", "Fishcurry", "Meatcurry" myfaves "Rice", "Fishcurry", "Meatcurry" **

3. Insert an R code chunk below. Show the `summary` of the `Orange` dataset.
Run a linear regression using the `lm` function to predict `circumference` from
`age` and assign the result. Show the `summary` of the fit object that you
assigned.

**= 
 > summary(Orange)
  Tree       age         circumference  
  3:7   Min.   : 118.0   Min.   : 30.0  
  1:7   1st Qu.: 484.0   1st Qu.: 65.5  
  5:7   Median :1004.0   Median :115.0  
  2:7   Mean   : 922.1   Mean   :115.9  
  4:7   3rd Qu.:1372.0   3rd Qu.:161.5  
        Max.   :1582.0   Max.   :214.0  
        

lm(circumference 1 + age, data = Orange) - my.model summary(my.model) 
lm(formula = circumference minus one plus age, data = Orange) 
Residues: 1Q minimum 3Q Median -46.310 -14.946 -0.076 19.697 45.111 Max -46.310 -14.946 -0.076 
Estimate Std. Coefficients 17.399650 8.622660 2.018 0.0518. age 0.106770 0.008277 12.900 1.93e-14 *** — Error t value Pr(>|t|) (Intercept) 17.399650 8.622660 2.018 0.0518. Codes of significance: 0 ‘' 0.001 ‘' 0.01 ‘' 0.05 ‘.' 0.1 ‘

4. Add an RMarkdown weblink (in link format) below to your favorite R reference
website.

=
 rmarkdown.rstudio.com/authoring_basics.html 



5. Replace the author field in the `yaml` header with your name and then
successfully `knit` the RMarkdown document into a Word document.


=
 title: "Distill for R Markdown"
 author:
   - name: "Joyessa"
    
   affiliation: RStudio
    affiliation_url: https://www.rstudio.com
 output: distill::distill_article


6. Follow the [Pull Request instructions on GitHub](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)
to submit your assignment via GitHub as a Pull Request to the [Assignment8][1]
repository.

[1]: https://github.com/CUNYSPHCode/Assignment8

